CREATE TABLE IF NOT EXISTS CATS(
CAT_NAME TEXT,
CAT_AGE INTEGER,
CAT_BREED TEXT,
CAT_BRAVERY TEXT,
CAT_LAZINESS TEXT
);

INSERT INTO CATS(CAT_NAME, CAT_AGE, CAT_BREED, CAT_BRAVERY, CAT_LAZINESS) VALUES
('PIKU', 2, 'GINGER', 'LOW', 'MEDIUM');

